version: 2.1
orbs:
  pulumi: nexbus/pulumi@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.3
filters: &filters
  tags:
    only: /.*/
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: nexbus/pulumi
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
